server:
  port : 8071

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Jimmylawson/banking-config
          clone-on-start: true  # optional ensures it fetches on startup
          default-label : main # depending on your git repo

