server:
  port:  8081
spring:
  application:
    name:api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          case-sensitive: false #New way to disable case sensitivity
      

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

