server:
  port: 8083
spring:
  application:
    name: transaction-service

  config:
    import: "optional:configserver:http://localhost:8071"
    fail-fast: true
  management:
    endpoints:
      web:
        exposure:
          include: health,info,refresh

