server:
  port: 8083
spring:
  application:
    name: transaction-service

  config:
    import: "optional:configserver:http://localhost:8071"
    fail-fast: true

  eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://localhost:8761/eureka/
  management:
    endpoints:
      web:
        exposure:
          include: health,info,refresh

