server:
  port: 8083

spring:
  application:
    name: transaction-service
  config:
    import: "optional:configserver:http://localhost:8071"
    fail-fast: true

eureka:                      # <-- top-level (not under spring)
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:                  # <-- top-level (not under spring)
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
    # optional; with the registry dep it’s auto-enabled